blank_issues_enabled: false
contact_links:
  - name: "ğŸ™‹â€â™‚ï¸ Ask the community a question!"
    about: Have a question, that might not be a bug? Wondering how to solve a problem? Ask away!
    url: "${repo.url}/discussions/new?category=q-a"
  - name: "ğŸ‰ Show us what you've made!"
    about: Have you built something using ${repo.name}, and want to show others? Post here!
    url: "${repo.url}/discussions/new?category=show-and-tell"
  - name: "âœ‹ Additional support information"
    about: Looking for something else? Check here.
    url: "${repo.url}/blob/${repo.default_branch}/SUPPORT.md"
  - name: "ğŸ’¬ Discord chat"
    about: On-topic and off-topic discussions.
    url: "${user.chat_url}"
